owner: moec-dev
repo: upptime

sites:
  - name: Index
    url: https://www.moec.dev

status-website:
  cname: status.moec.dev
  logoUrl: https://avatars.githubusercontent.com/u/219799697
  name: MOECDEV Upptime
  introTitle: "This page showing status about **MOECDEV** Web Service."
  introMessage: Welcome to this page by MOECDEV! You can see all running status about MOECDEV in this page! 
  navbar:
    - title: Status
      href: /
    - title: Index
      href: https://www.moec.dev/
    - title: GitHub
      href: https://github.com/moec-dev
